### ISSUE TITLE
Sample script won't validate on JSONLint

### ISSUE THREAD

**Issue by larrybradshaw-thinkdifferent** [fholgado/homebridge-simplisafe-security-system#4]
This sample script provided gives this error

Error: Parse error on line 13:
...: "your@email.com", // your SimpliSafe u
-----------------------^
Expecting 'STRING', got 'undefined'

`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"accessories": [{
		"accessory": "Homebridge-SimpliSafe",
		"name": "Alarm System",
		"auth": {
			"username": "your@email.com", // your SimpliSafe username
			"password": "yourawesomepassword" // your SimpliSafe password
		}
	}]
}`

**Comment by apexad** [comment]
Try removing the `// your SimpliSafe username` and `// your SimpliSafe password` parts

**Comment by larrybradshaw-thinkdifferent** [comment]
That worked in getting the code to validate. Thanks!
